CREATE TABLE Crop_calendar(data_id INTEGER, country VARCHAR NOT NULL, crop VARCHAR NOT NULL, plant_start INTEGER, plant_end INTEGER, plant_range INTEGER, harvest_start INTEGER, harvest_end INTEGER, harvest_range INTEGER, temp_average FLOAT, precip_average FLOAT, CHECK((plant_start BETWEEN 1 AND 365)), CHECK((plant_end BETWEEN 1 AND 365)), CHECK((plant_range BETWEEN 1 AND 365)), CHECK((harvest_start BETWEEN 1 AND 365)), CHECK((harvest_end BETWEEN 1 AND 365)), CHECK((harvest_range BETWEEN 1 AND 365)), PRIMARY KEY(data_id));
CREATE TABLE Crop_calendar_2(data_id BIGINT, country VARCHAR, crop VARCHAR, plant_start BIGINT, plant_end BIGINT, plant_range BIGINT, harvest_start VARCHAR, harvest_end VARCHAR, harvest_range VARCHAR, temp_average VARCHAR, precip_average VARCHAR);
CREATE TABLE Crop_yield(country VARCHAR NOT NULL, item VARCHAR NOT NULL, item_code_cpc INTEGER NOT NULL, element VARCHAR NOT NULL, element_code INTEGER NOT NULL, "year" INTEGER NOT NULL, unit VARCHAR NOT NULL, "value" FLOAT, flag_description VARCHAR NOT NULL, flag VARCHAR NOT NULL, "domain" VARCHAR NOT NULL, domain_code VARCHAR NOT NULL, unique_id INTEGER, PRIMARY KEY(unique_id));
CREATE TABLE Crop_yield_2(country VARCHAR, item VARCHAR, item_code_cpc VARCHAR, element VARCHAR, element_code BIGINT, "year" BIGINT, unit VARCHAR, "value" VARCHAR, flag_description VARCHAR, flag VARCHAR, "domain" VARCHAR, domain_code VARCHAR, unique_id BIGINT);
CREATE TABLE Personnel(Abbreviation VARCHAR PRIMARY KEY, "Name" VARCHAR NOT NULL UNIQUE);
CREATE TABLE Site(Code VARCHAR PRIMARY KEY, Site_name VARCHAR NOT NULL UNIQUE, "Location" VARCHAR NOT NULL, Latitude FLOAT NOT NULL, Longitude FLOAT NOT NULL, Area FLOAT NOT NULL, CHECK((Latitude BETWEEN -90 AND 90)), CHECK((Longitude BETWEEN -180 AND 180)), CHECK((Area > 0)), UNIQUE(Latitude, Longitude));
CREATE TABLE Species(Code VARCHAR PRIMARY KEY, Common_name VARCHAR NOT NULL UNIQUE, Scientific_name VARCHAR, Relevance VARCHAR);
CREATE TABLE Bird_nests(Book_page VARCHAR, "Year" INTEGER NOT NULL, Site VARCHAR NOT NULL, Nest_ID VARCHAR PRIMARY KEY, Species VARCHAR NOT NULL, Observer VARCHAR, Date_found DATE NOT NULL, how_found VARCHAR, Clutch_max INTEGER, floatAge FLOAT, ageMethod VARCHAR, CHECK(("Year" BETWEEN 1950 AND 2015)), CHECK((Date_found BETWEEN CAST(("Year" || '-01-01') AS DATE) AND CAST(("Year" || '-12-31') AS DATE))), CHECK((how_found IN ('searcher', 'rope', 'bander'))), CHECK((Clutch_max BETWEEN 0 AND 20)), CHECK((floatAge BETWEEN 0 AND 30)), CHECK((ageMethod IN ('float', 'lay', 'hatch'))), FOREIGN KEY (Site) REFERENCES Site(Code), FOREIGN KEY (Species) REFERENCES Species(Code), FOREIGN KEY (Observer) REFERENCES Personnel(Abbreviation));
CREATE TABLE Camp_assignment("Year" INTEGER NOT NULL, Site VARCHAR NOT NULL, Observer VARCHAR NOT NULL, "Start" DATE, "End" DATE, CHECK(("Year" BETWEEN 1950 AND 2015)), FOREIGN KEY (Site) REFERENCES Site(Code), FOREIGN KEY (Observer) REFERENCES Personnel(Abbreviation), CHECK(("Start" <= "End")), CHECK(("Start" BETWEEN CAST(("Year" || '-01-01') AS DATE) AND CAST(("Year" || '-12-31') AS DATE))), CHECK(("End" BETWEEN CAST(("Year" || '-01-01') AS DATE) AND CAST(("Year" || '-12-31') AS DATE))));
CREATE TABLE Snow_cover(Site VARCHAR, "Year" INTEGER NOT NULL, Date DATE, Plot VARCHAR, "Location" VARCHAR, Snow_cover FLOAT, Water_cover FLOAT, Land_cover FLOAT, Total_cover FLOAT, Observer VARCHAR, Notes VARCHAR, CHECK(("Year" BETWEEN 1990 AND 2020)), CHECK((Snow_cover BETWEEN 0 AND 130)), CHECK((Water_cover BETWEEN 0 AND 130)), CHECK((Land_cover BETWEEN 0 AND 130)), CHECK((Total_cover BETWEEN 0 AND 130)), PRIMARY KEY(Site, Plot, "Location", Date), FOREIGN KEY (Site) REFERENCES Site(Code));
CREATE TABLE Bird_eggs(Book_page VARCHAR, "Year" INTEGER NOT NULL, Site VARCHAR NOT NULL, Nest_ID VARCHAR, Egg_num INTEGER, Length FLOAT NOT NULL, Width FLOAT NOT NULL, CHECK(("Year" BETWEEN 1950 AND 2015)), CHECK((Egg_num BETWEEN 1 AND 20)), CHECK(((Length > 0) AND (Length < 100))), CHECK(((Width > 0) AND (Width < 100))), PRIMARY KEY(Nest_ID, Egg_num), FOREIGN KEY (Site) REFERENCES Site(Code), FOREIGN KEY (Nest_ID) REFERENCES Bird_nests(Nest_ID));
CREATE VIEW my_nests AS SELECT Nest_ID, any_value(Observer) AS Observer, count_star() AS Num_eggs FROM Bird_nests INNER JOIN Bird_eggs USING (Nest_ID) WHERE (Nest_ID ~~ '13B%') GROUP BY Nest_ID;
CREATE VIEW Site_avg_snowcover AS SELECT Site, avg(Snow_cover) AS avg_snow_cover FROM Snow_cover GROUP BY Site ORDER BY avg_snow_cover DESC LIMIT 5;

